################################################################################
#	@brief		makefile for factorial project
#	@author		llChameleoNll <HoYa128@gmail.com>
#	@version	v1.0
#	@note
#		2018.01.05	Created.
################################################################################

CC      = clang-cl
CFLAGS  = -Os

all: factorial

factorial: factorial.c
	$(CC) $(CFLAGS) -o factorial -c factorial.c

clean:
	$(RM) factorial
